// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthCallbackGetOperation            OperationName = "AuthCallbackGet"
	AuthLoginGetOperation               OperationName = "AuthLoginGet"
	AuthLogoutPostOperation             OperationName = "AuthLogoutPost"
	AuthMeGetOperation                  OperationName = "AuthMeGet"
	AuthRefreshPostOperation            OperationName = "AuthRefreshPost"
	FriendsGetOperation                 OperationName = "FriendsGet"
	FriendsPostOperation                OperationName = "FriendsPost"
	FriendsUserIDDeleteOperation        OperationName = "FriendsUserIDDelete"
	GenresGetOperation                  OperationName = "GenresGet"
	GoalsGetOperation                   OperationName = "GoalsGet"
	GoalsGoalIDDeleteOperation          OperationName = "GoalsGoalIDDelete"
	GoalsGoalIDGetOperation             OperationName = "GoalsGoalIDGet"
	GoalsGoalIDPutOperation             OperationName = "GoalsGoalIDPut"
	GoalsPostOperation                  OperationName = "GoalsPost"
	ImagesImageIDGetOperation           OperationName = "ImagesImageIDGet"
	ImagesPostOperation                 OperationName = "ImagesPost"
	PostsGetOperation                   OperationName = "PostsGet"
	PostsPostOperation                  OperationName = "PostsPost"
	PostsPostIDDeleteOperation          OperationName = "PostsPostIDDelete"
	PostsPostIDGetOperation             OperationName = "PostsPostIDGet"
	PostsPostIDPutOperation             OperationName = "PostsPostIDPut"
	PostsPostIDReactionsDeleteOperation OperationName = "PostsPostIDReactionsDelete"
	PostsPostIDReactionsGetOperation    OperationName = "PostsPostIDReactionsGet"
	PostsPostIDReactionsPostOperation   OperationName = "PostsPostIDReactionsPost"
	TimelineGetOperation                OperationName = "TimelineGet"
	UsersUserIDDeleteOperation          OperationName = "UsersUserIDDelete"
	UsersUserIDFriendsGetOperation      OperationName = "UsersUserIDFriendsGet"
	UsersUserIDGetOperation             OperationName = "UsersUserIDGet"
	UsersUserIDGoalsGetOperation        OperationName = "UsersUserIDGoalsGet"
	UsersUserIDIconDeleteOperation      OperationName = "UsersUserIDIconDelete"
	UsersUserIDIconGetOperation         OperationName = "UsersUserIDIconGet"
	UsersUserIDIconPostOperation        OperationName = "UsersUserIDIconPost"
	UsersUserIDPostsGetOperation        OperationName = "UsersUserIDPostsGet"
	UsersUserIDPutOperation             OperationName = "UsersUserIDPut"
)
