// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"time"

	"github.com/google/uuid"
	ht "github.com/ogen-go/ogen/http"
)

func (s *GeneralErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// AuthCallbackGetNoContent is response for AuthCallbackGet operation.
type AuthCallbackGetNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *AuthCallbackGetNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *AuthCallbackGetNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*AuthCallbackGetNoContent) authCallbackGetRes() {}

// AuthLoginGetMovedPermanently is response for AuthLoginGet operation.
type AuthLoginGetMovedPermanently struct {
	Location OptString
}

// GetLocation returns the value of Location.
func (s *AuthLoginGetMovedPermanently) GetLocation() OptString {
	return s.Location
}

// SetLocation sets the value of Location.
func (s *AuthLoginGetMovedPermanently) SetLocation(val OptString) {
	s.Location = val
}

// AuthLogoutPostNoContent is response for AuthLogoutPost operation.
type AuthLogoutPostNoContent struct{}

// AuthRefreshPostNoContent is response for AuthRefreshPost operation.
type AuthRefreshPostNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *AuthRefreshPostNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *AuthRefreshPostNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*AuthRefreshPostNoContent) authRefreshPostRes() {}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) authCallbackGetRes()         {}
func (*Error) authMeGetRes()               {}
func (*Error) authRefreshPostRes()         {}
func (*Error) friendsGetRes()              {}
func (*Error) goalsGoalIDGetRes()          {}
func (*Error) imagesImageIDGetRes()        {}
func (*Error) postsPostIDGetRes()          {}
func (*Error) postsPostIDReactionsGetRes() {}
func (*Error) usersUserIDIconGetRes()      {}

type FriendsGetOKApplicationJSON []uuid.UUID

func (*FriendsGetOKApplicationJSON) friendsGetRes() {}

type FriendsPostBadRequest Error

func (*FriendsPostBadRequest) friendsPostRes() {}

// FriendsPostCreated is response for FriendsPost operation.
type FriendsPostCreated struct{}

func (*FriendsPostCreated) friendsPostRes() {}

type FriendsPostNotFound Error

func (*FriendsPostNotFound) friendsPostRes() {}

type FriendsPostReq struct {
	// 対象ユーザーID.
	UserID uuid.UUID `json:"user_id"`
}

// GetUserID returns the value of UserID.
func (s *FriendsPostReq) GetUserID() uuid.UUID {
	return s.UserID
}

// SetUserID sets the value of UserID.
func (s *FriendsPostReq) SetUserID(val uuid.UUID) {
	s.UserID = val
}

type FriendsPostUnauthorized Error

func (*FriendsPostUnauthorized) friendsPostRes() {}

// FriendsUserIDDeleteNoContent is response for FriendsUserIDDelete operation.
type FriendsUserIDDeleteNoContent struct{}

func (*FriendsUserIDDeleteNoContent) friendsUserIDDeleteRes() {}

type FriendsUserIDDeleteNotFound Error

func (*FriendsUserIDDeleteNotFound) friendsUserIDDeleteRes() {}

type FriendsUserIDDeleteUnauthorized Error

func (*FriendsUserIDDeleteUnauthorized) friendsUserIDDeleteRes() {}

// GeneralErrorStatusCode wraps Error with StatusCode.
type GeneralErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *GeneralErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GeneralErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GeneralErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GeneralErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Genre
type Genre struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetID returns the value of ID.
func (s *Genre) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Genre) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Genre) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Genre) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/Goal
type Goal struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	Deadline  OptDate   `json:"deadline"`
}

// GetID returns the value of ID.
func (s *Goal) GetID() uuid.UUID {
	return s.ID
}

// GetUserID returns the value of UserID.
func (s *Goal) GetUserID() uuid.UUID {
	return s.UserID
}

// GetTitle returns the value of Title.
func (s *Goal) GetTitle() string {
	return s.Title
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Goal) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetDeadline returns the value of Deadline.
func (s *Goal) GetDeadline() OptDate {
	return s.Deadline
}

// SetID sets the value of ID.
func (s *Goal) SetID(val uuid.UUID) {
	s.ID = val
}

// SetUserID sets the value of UserID.
func (s *Goal) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetTitle sets the value of Title.
func (s *Goal) SetTitle(val string) {
	s.Title = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Goal) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetDeadline sets the value of Deadline.
func (s *Goal) SetDeadline(val OptDate) {
	s.Deadline = val
}

func (*Goal) goalsGoalIDGetRes() {}
func (*Goal) goalsGoalIDPutRes() {}
func (*Goal) goalsPostRes()      {}

// Ref: #/components/schemas/GoalRequest
type GoalRequest struct {
	Title    string  `json:"title"`
	Deadline OptDate `json:"deadline"`
}

// GetTitle returns the value of Title.
func (s *GoalRequest) GetTitle() string {
	return s.Title
}

// GetDeadline returns the value of Deadline.
func (s *GoalRequest) GetDeadline() OptDate {
	return s.Deadline
}

// SetTitle sets the value of Title.
func (s *GoalRequest) SetTitle(val string) {
	s.Title = val
}

// SetDeadline sets the value of Deadline.
func (s *GoalRequest) SetDeadline(val OptDate) {
	s.Deadline = val
}

type GoalsGetBadRequest Error

func (*GoalsGetBadRequest) goalsGetRes() {}

type GoalsGetOKApplicationJSON []Goal

func (*GoalsGetOKApplicationJSON) goalsGetRes() {}

type GoalsGetUnauthorized Error

func (*GoalsGetUnauthorized) goalsGetRes() {}

// GoalsGoalIDDeleteNoContent is response for GoalsGoalIDDelete operation.
type GoalsGoalIDDeleteNoContent struct{}

func (*GoalsGoalIDDeleteNoContent) goalsGoalIDDeleteRes() {}

type GoalsGoalIDDeleteNotFound Error

func (*GoalsGoalIDDeleteNotFound) goalsGoalIDDeleteRes() {}

type GoalsGoalIDDeleteUnauthorized Error

func (*GoalsGoalIDDeleteUnauthorized) goalsGoalIDDeleteRes() {}

type GoalsGoalIDPutBadRequest Error

func (*GoalsGoalIDPutBadRequest) goalsGoalIDPutRes() {}

type GoalsGoalIDPutNotFound Error

func (*GoalsGoalIDPutNotFound) goalsGoalIDPutRes() {}

type GoalsGoalIDPutUnauthorized Error

func (*GoalsGoalIDPutUnauthorized) goalsGoalIDPutRes() {}

type GoalsPostBadRequest Error

func (*GoalsPostBadRequest) goalsPostRes() {}

type GoalsPostUnauthorized Error

func (*GoalsPostUnauthorized) goalsPostRes() {}

// Ref: #/components/schemas/Image
type Image struct {
	ID  uuid.UUID `json:"id"`
	URL string    `json:"url"`
}

// GetID returns the value of ID.
func (s *Image) GetID() uuid.UUID {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Image) GetURL() string {
	return s.URL
}

// SetID sets the value of ID.
func (s *Image) SetID(val uuid.UUID) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Image) SetURL(val string) {
	s.URL = val
}

func (*Image) imagesPostRes() {}

type ImagesImageIDGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ImagesImageIDGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*ImagesImageIDGetOK) imagesImageIDGetRes() {}

type ImagesPostBadRequest Error

func (*ImagesPostBadRequest) imagesPostRes() {}

type ImagesPostReq struct {
	Image OptMultipartFile `json:"image"`
}

// GetImage returns the value of Image.
func (s *ImagesPostReq) GetImage() OptMultipartFile {
	return s.Image
}

// SetImage sets the value of Image.
func (s *ImagesPostReq) SetImage(val OptMultipartFile) {
	s.Image = val
}

type ImagesPostUnauthorized Error

func (*ImagesPostUnauthorized) imagesPostRes() {}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptImagesPostReq returns new OptImagesPostReq with value set to v.
func NewOptImagesPostReq(v ImagesPostReq) OptImagesPostReq {
	return OptImagesPostReq{
		Value: v,
		Set:   true,
	}
}

// OptImagesPostReq is optional ImagesPostReq.
type OptImagesPostReq struct {
	Value ImagesPostReq
	Set   bool
}

// IsSet returns true if OptImagesPostReq was set.
func (o OptImagesPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptImagesPostReq) Reset() {
	var v ImagesPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptImagesPostReq) SetTo(v ImagesPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptImagesPostReq) Get() (v ImagesPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptImagesPostReq) Or(d ImagesPostReq) ImagesPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMultipartFile returns new OptMultipartFile with value set to v.
func NewOptMultipartFile(v ht.MultipartFile) OptMultipartFile {
	return OptMultipartFile{
		Value: v,
		Set:   true,
	}
}

// OptMultipartFile is optional ht.MultipartFile.
type OptMultipartFile struct {
	Value ht.MultipartFile
	Set   bool
}

// IsSet returns true if OptMultipartFile was set.
func (o OptMultipartFile) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMultipartFile) Reset() {
	var v ht.MultipartFile
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMultipartFile) SetTo(v ht.MultipartFile) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMultipartFile) Get() (v ht.MultipartFile, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMultipartFile) Or(d ht.MultipartFile) ht.MultipartFile {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUsersUserIDIconPostReq returns new OptUsersUserIDIconPostReq with value set to v.
func NewOptUsersUserIDIconPostReq(v UsersUserIDIconPostReq) OptUsersUserIDIconPostReq {
	return OptUsersUserIDIconPostReq{
		Value: v,
		Set:   true,
	}
}

// OptUsersUserIDIconPostReq is optional UsersUserIDIconPostReq.
type OptUsersUserIDIconPostReq struct {
	Value UsersUserIDIconPostReq
	Set   bool
}

// IsSet returns true if OptUsersUserIDIconPostReq was set.
func (o OptUsersUserIDIconPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUsersUserIDIconPostReq) Reset() {
	var v UsersUserIDIconPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUsersUserIDIconPostReq) SetTo(v UsersUserIDIconPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUsersUserIDIconPostReq) Get() (v UsersUserIDIconPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUsersUserIDIconPostReq) Or(d UsersUserIDIconPostReq) UsersUserIDIconPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Post
type Post struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	GoalID    uuid.UUID `json:"goal_id"`
	Content   string    `json:"content"`
	ImageUrls []string  `json:"image_urls"`
	// リアクション（いいね）の数.
	ReactionCount int       `json:"reaction_count"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Post) GetID() uuid.UUID {
	return s.ID
}

// GetUserID returns the value of UserID.
func (s *Post) GetUserID() uuid.UUID {
	return s.UserID
}

// GetGoalID returns the value of GoalID.
func (s *Post) GetGoalID() uuid.UUID {
	return s.GoalID
}

// GetContent returns the value of Content.
func (s *Post) GetContent() string {
	return s.Content
}

// GetImageUrls returns the value of ImageUrls.
func (s *Post) GetImageUrls() []string {
	return s.ImageUrls
}

// GetReactionCount returns the value of ReactionCount.
func (s *Post) GetReactionCount() int {
	return s.ReactionCount
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Post) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Post) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Post) SetID(val uuid.UUID) {
	s.ID = val
}

// SetUserID sets the value of UserID.
func (s *Post) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetGoalID sets the value of GoalID.
func (s *Post) SetGoalID(val uuid.UUID) {
	s.GoalID = val
}

// SetContent sets the value of Content.
func (s *Post) SetContent(val string) {
	s.Content = val
}

// SetImageUrls sets the value of ImageUrls.
func (s *Post) SetImageUrls(val []string) {
	s.ImageUrls = val
}

// SetReactionCount sets the value of ReactionCount.
func (s *Post) SetReactionCount(val int) {
	s.ReactionCount = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Post) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Post) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Post) postsPostIDGetRes() {}
func (*Post) postsPostIDPutRes() {}
func (*Post) postsPostRes()      {}

// Ref: #/components/schemas/PostRequest
type PostRequest struct {
	GoalID   uuid.UUID   `json:"goal_id"`
	Content  string      `json:"content"`
	ImageIds []uuid.UUID `json:"image_ids"`
}

// GetGoalID returns the value of GoalID.
func (s *PostRequest) GetGoalID() uuid.UUID {
	return s.GoalID
}

// GetContent returns the value of Content.
func (s *PostRequest) GetContent() string {
	return s.Content
}

// GetImageIds returns the value of ImageIds.
func (s *PostRequest) GetImageIds() []uuid.UUID {
	return s.ImageIds
}

// SetGoalID sets the value of GoalID.
func (s *PostRequest) SetGoalID(val uuid.UUID) {
	s.GoalID = val
}

// SetContent sets the value of Content.
func (s *PostRequest) SetContent(val string) {
	s.Content = val
}

// SetImageIds sets the value of ImageIds.
func (s *PostRequest) SetImageIds(val []uuid.UUID) {
	s.ImageIds = val
}

type PostsGetBadRequest Error

func (*PostsGetBadRequest) postsGetRes() {}

type PostsGetOKApplicationJSON []Post

func (*PostsGetOKApplicationJSON) postsGetRes() {}

type PostsGetUnauthorized Error

func (*PostsGetUnauthorized) postsGetRes() {}

type PostsPostBadRequest Error

func (*PostsPostBadRequest) postsPostRes() {}

// PostsPostIDDeleteNoContent is response for PostsPostIDDelete operation.
type PostsPostIDDeleteNoContent struct{}

func (*PostsPostIDDeleteNoContent) postsPostIDDeleteRes() {}

type PostsPostIDDeleteNotFound Error

func (*PostsPostIDDeleteNotFound) postsPostIDDeleteRes() {}

type PostsPostIDDeleteUnauthorized Error

func (*PostsPostIDDeleteUnauthorized) postsPostIDDeleteRes() {}

type PostsPostIDPutBadRequest Error

func (*PostsPostIDPutBadRequest) postsPostIDPutRes() {}

type PostsPostIDPutNotFound Error

func (*PostsPostIDPutNotFound) postsPostIDPutRes() {}

type PostsPostIDPutUnauthorized Error

func (*PostsPostIDPutUnauthorized) postsPostIDPutRes() {}

// PostsPostIDReactionsDeleteNoContent is response for PostsPostIDReactionsDelete operation.
type PostsPostIDReactionsDeleteNoContent struct{}

func (*PostsPostIDReactionsDeleteNoContent) postsPostIDReactionsDeleteRes() {}

type PostsPostIDReactionsDeleteNotFound Error

func (*PostsPostIDReactionsDeleteNotFound) postsPostIDReactionsDeleteRes() {}

type PostsPostIDReactionsDeleteUnauthorized Error

func (*PostsPostIDReactionsDeleteUnauthorized) postsPostIDReactionsDeleteRes() {}

type PostsPostIDReactionsGetOKApplicationJSON []Reaction

func (*PostsPostIDReactionsGetOKApplicationJSON) postsPostIDReactionsGetRes() {}

// PostsPostIDReactionsPostCreated is response for PostsPostIDReactionsPost operation.
type PostsPostIDReactionsPostCreated struct{}

func (*PostsPostIDReactionsPostCreated) postsPostIDReactionsPostRes() {}

type PostsPostIDReactionsPostNotFound Error

func (*PostsPostIDReactionsPostNotFound) postsPostIDReactionsPostRes() {}

type PostsPostIDReactionsPostUnauthorized Error

func (*PostsPostIDReactionsPostUnauthorized) postsPostIDReactionsPostRes() {}

type PostsPostUnauthorized Error

func (*PostsPostUnauthorized) postsPostRes() {}

// Ref: #/components/schemas/Reaction
type Reaction struct {
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

// GetUserID returns the value of UserID.
func (s *Reaction) GetUserID() uuid.UUID {
	return s.UserID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Reaction) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetUserID sets the value of UserID.
func (s *Reaction) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Reaction) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

type TimelineGetBadRequest Error

func (*TimelineGetBadRequest) timelineGetRes() {}

type TimelineGetOKApplicationJSON []Post

func (*TimelineGetOKApplicationJSON) timelineGetRes() {}

type TimelineGetUnauthorized Error

func (*TimelineGetUnauthorized) timelineGetRes() {}

// Ref: #/components/schemas/User
type User struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Birthday OptDate     `json:"birthday"`
	Genres   []uuid.UUID `json:"genres"`
	Hometown OptString   `json:"hometown"`
	Bio      OptString   `json:"bio"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetBirthday returns the value of Birthday.
func (s *User) GetBirthday() OptDate {
	return s.Birthday
}

// GetGenres returns the value of Genres.
func (s *User) GetGenres() []uuid.UUID {
	return s.Genres
}

// GetHometown returns the value of Hometown.
func (s *User) GetHometown() OptString {
	return s.Hometown
}

// GetBio returns the value of Bio.
func (s *User) GetBio() OptString {
	return s.Bio
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetBirthday sets the value of Birthday.
func (s *User) SetBirthday(val OptDate) {
	s.Birthday = val
}

// SetGenres sets the value of Genres.
func (s *User) SetGenres(val []uuid.UUID) {
	s.Genres = val
}

// SetHometown sets the value of Hometown.
func (s *User) SetHometown(val OptString) {
	s.Hometown = val
}

// SetBio sets the value of Bio.
func (s *User) SetBio(val OptString) {
	s.Bio = val
}

func (*User) authMeGetRes()      {}
func (*User) usersUserIDGetRes() {}
func (*User) usersUserIDPutRes() {}

// Ref: #/components/schemas/UserRequest
type UserRequest struct {
	Name     string      `json:"name"`
	Birthday OptDate     `json:"birthday"`
	Genres   []uuid.UUID `json:"genres"`
	Hometown OptString   `json:"hometown"`
	Bio      OptString   `json:"bio"`
}

// GetName returns the value of Name.
func (s *UserRequest) GetName() string {
	return s.Name
}

// GetBirthday returns the value of Birthday.
func (s *UserRequest) GetBirthday() OptDate {
	return s.Birthday
}

// GetGenres returns the value of Genres.
func (s *UserRequest) GetGenres() []uuid.UUID {
	return s.Genres
}

// GetHometown returns the value of Hometown.
func (s *UserRequest) GetHometown() OptString {
	return s.Hometown
}

// GetBio returns the value of Bio.
func (s *UserRequest) GetBio() OptString {
	return s.Bio
}

// SetName sets the value of Name.
func (s *UserRequest) SetName(val string) {
	s.Name = val
}

// SetBirthday sets the value of Birthday.
func (s *UserRequest) SetBirthday(val OptDate) {
	s.Birthday = val
}

// SetGenres sets the value of Genres.
func (s *UserRequest) SetGenres(val []uuid.UUID) {
	s.Genres = val
}

// SetHometown sets the value of Hometown.
func (s *UserRequest) SetHometown(val OptString) {
	s.Hometown = val
}

// SetBio sets the value of Bio.
func (s *UserRequest) SetBio(val OptString) {
	s.Bio = val
}

type UsersUserIDDeleteBadRequest Error

func (*UsersUserIDDeleteBadRequest) usersUserIDDeleteRes() {}

// UsersUserIDDeleteNoContent is response for UsersUserIDDelete operation.
type UsersUserIDDeleteNoContent struct{}

func (*UsersUserIDDeleteNoContent) usersUserIDDeleteRes() {}

type UsersUserIDDeleteNotFound Error

func (*UsersUserIDDeleteNotFound) usersUserIDDeleteRes() {}

type UsersUserIDDeleteUnauthorized Error

func (*UsersUserIDDeleteUnauthorized) usersUserIDDeleteRes() {}

type UsersUserIDFriendsGetNotFound Error

func (*UsersUserIDFriendsGetNotFound) usersUserIDFriendsGetRes() {}

type UsersUserIDFriendsGetOKApplicationJSON []uuid.UUID

func (*UsersUserIDFriendsGetOKApplicationJSON) usersUserIDFriendsGetRes() {}

type UsersUserIDFriendsGetUnauthorized Error

func (*UsersUserIDFriendsGetUnauthorized) usersUserIDFriendsGetRes() {}

type UsersUserIDGetNotFound Error

func (*UsersUserIDGetNotFound) usersUserIDGetRes() {}

type UsersUserIDGetUnauthorized Error

func (*UsersUserIDGetUnauthorized) usersUserIDGetRes() {}

type UsersUserIDGoalsGetBadRequest Error

func (*UsersUserIDGoalsGetBadRequest) usersUserIDGoalsGetRes() {}

type UsersUserIDGoalsGetNotFound Error

func (*UsersUserIDGoalsGetNotFound) usersUserIDGoalsGetRes() {}

type UsersUserIDGoalsGetOKApplicationJSON []Goal

func (*UsersUserIDGoalsGetOKApplicationJSON) usersUserIDGoalsGetRes() {}

// UsersUserIDIconDeleteNoContent is response for UsersUserIDIconDelete operation.
type UsersUserIDIconDeleteNoContent struct{}

func (*UsersUserIDIconDeleteNoContent) usersUserIDIconDeleteRes() {}

type UsersUserIDIconDeleteNotFound Error

func (*UsersUserIDIconDeleteNotFound) usersUserIDIconDeleteRes() {}

type UsersUserIDIconDeleteUnauthorized Error

func (*UsersUserIDIconDeleteUnauthorized) usersUserIDIconDeleteRes() {}

type UsersUserIDIconGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s UsersUserIDIconGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*UsersUserIDIconGetOK) usersUserIDIconGetRes() {}

type UsersUserIDIconPostBadRequest Error

func (*UsersUserIDIconPostBadRequest) usersUserIDIconPostRes() {}

// UsersUserIDIconPostNoContent is response for UsersUserIDIconPost operation.
type UsersUserIDIconPostNoContent struct{}

func (*UsersUserIDIconPostNoContent) usersUserIDIconPostRes() {}

type UsersUserIDIconPostReq struct {
	Icon OptMultipartFile `json:"icon"`
}

// GetIcon returns the value of Icon.
func (s *UsersUserIDIconPostReq) GetIcon() OptMultipartFile {
	return s.Icon
}

// SetIcon sets the value of Icon.
func (s *UsersUserIDIconPostReq) SetIcon(val OptMultipartFile) {
	s.Icon = val
}

type UsersUserIDIconPostUnauthorized Error

func (*UsersUserIDIconPostUnauthorized) usersUserIDIconPostRes() {}

type UsersUserIDPostsGetBadRequest Error

func (*UsersUserIDPostsGetBadRequest) usersUserIDPostsGetRes() {}

type UsersUserIDPostsGetNotFound Error

func (*UsersUserIDPostsGetNotFound) usersUserIDPostsGetRes() {}

type UsersUserIDPostsGetOKApplicationJSON []Post

func (*UsersUserIDPostsGetOKApplicationJSON) usersUserIDPostsGetRes() {}

type UsersUserIDPutBadRequest Error

func (*UsersUserIDPutBadRequest) usersUserIDPutRes() {}

type UsersUserIDPutNotFound Error

func (*UsersUserIDPutNotFound) usersUserIDPutRes() {}

type UsersUserIDPutUnauthorized Error

func (*UsersUserIDPutUnauthorized) usersUserIDPutRes() {}
