// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"

				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "callback"

					if l := len("callback"); len(elem) >= l && elem[0:l] == "callback" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleAuthCallbackGetRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				case 'l': // Prefix: "log"

					if l := len("log"); len(elem) >= l && elem[0:l] == "log" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'i': // Prefix: "in"

						if l := len("in"); len(elem) >= l && elem[0:l] == "in" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleAuthLoginGetRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET")
							}

							return
						}

					case 'o': // Prefix: "out"

						if l := len("out"); len(elem) >= l && elem[0:l] == "out" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleAuthLogoutPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "POST")
							}

							return
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleAuthMeGetRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				}

			case 'f': // Prefix: "friends"

				if l := len("friends"); len(elem) >= l && elem[0:l] == "friends" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleFriendsGetRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleFriendsPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "user_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleFriendsUserIDDeleteRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE")
						}

						return
					}

				}

			case 'g': // Prefix: "goals"

				if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handleGoalsGetRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleGoalsPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "goal_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "DELETE":
							s.handleGoalsGoalIDDeleteRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleGoalsGoalIDGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleGoalsGoalIDPutRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PUT")
						}

						return
					}

				}

			case 'i': // Prefix: "images"

				if l := len("images"); len(elem) >= l && elem[0:l] == "images" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "POST":
						s.handleImagesPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "image_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleImagesImageIDGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

				}

			case 'p': // Prefix: "posts"

				if l := len("posts"); len(elem) >= l && elem[0:l] == "posts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "GET":
						s.handlePostsGetRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handlePostsPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "post_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handlePostsPostIDDeleteRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handlePostsPostIDGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handlePostsPostIDPutRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PUT")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/reactions"

						if l := len("/reactions"); len(elem) >= l && elem[0:l] == "/reactions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "DELETE":
								s.handlePostsPostIDReactionsDeleteRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "GET":
								s.handlePostsPostIDReactionsGetRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							case "POST":
								s.handlePostsPostIDReactionsPostRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "DELETE,GET,POST")
							}

							return
						}

					}

				}

			case 't': // Prefix: "timeline"

				if l := len("timeline"); len(elem) >= l && elem[0:l] == "timeline" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleTimelineGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch r.Method {
					case "POST":
						s.handleUsersPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "POST")
					}

					return
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "user_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch r.Method {
						case "DELETE":
							s.handleUsersUserIDDeleteRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "GET":
							s.handleUsersUserIDGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						case "PUT":
							s.handleUsersUserIDPutRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "DELETE,GET,PUT")
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'f': // Prefix: "friends"

							if l := len("friends"); len(elem) >= l && elem[0:l] == "friends" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleUsersUserIDFriendsGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'g': // Prefix: "goals"

							if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleUsersUserIDGoalsGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						case 'i': // Prefix: "icon"

							if l := len("icon"); len(elem) >= l && elem[0:l] == "icon" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleUsersUserIDIconDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "GET":
									s.handleUsersUserIDIconGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "POST":
									s.handleUsersUserIDIconPostRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,GET,POST")
								}

								return
							}

						case 'p': // Prefix: "posts"

							if l := len("posts"); len(elem) >= l && elem[0:l] == "posts" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleUsersUserIDPostsGetRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "GET")
								}

								return
							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "auth/"

				if l := len("auth/"); len(elem) >= l && elem[0:l] == "auth/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "callback"

					if l := len("callback"); len(elem) >= l && elem[0:l] == "callback" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = AuthCallbackGetOperation
							r.summary = "OIDCコールバック（コードをトークンに交換）"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/auth/callback"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'l': // Prefix: "log"

					if l := len("log"); len(elem) >= l && elem[0:l] == "log" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'i': // Prefix: "in"

						if l := len("in"); len(elem) >= l && elem[0:l] == "in" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = AuthLoginGetOperation
								r.summary = "OIDCログインを開始"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/auth/login"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "out"

						if l := len("out"); len(elem) >= l && elem[0:l] == "out" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = AuthLogoutPostOperation
								r.summary = "ログアウト"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/auth/logout"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = AuthMeGetOperation
							r.summary = "現在のユーザー情報を取得"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/auth/me"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'f': // Prefix: "friends"

				if l := len("friends"); len(elem) >= l && elem[0:l] == "friends" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = FriendsGetOperation
						r.summary = "自分のフレンド（フォロー）一覧取得"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/friends"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = FriendsPostOperation
						r.summary = "フレンド追加（フォロー）"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/friends"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "user_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = FriendsUserIDDeleteOperation
							r.summary = "フレンド削除（フォロー解除）"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/friends/{user_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'g': // Prefix: "goals"

				if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = GoalsGetOperation
						r.summary = "現在のユーザーの目標一覧取得"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/goals"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = GoalsPostOperation
						r.summary = "新規目標作成"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/goals"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "goal_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "DELETE":
							r.name = GoalsGoalIDDeleteOperation
							r.summary = "目標削除"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/goals/{goal_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = GoalsGoalIDGetOperation
							r.summary = "目標詳細取得"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/goals/{goal_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = GoalsGoalIDPutOperation
							r.summary = "目標更新"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/goals/{goal_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'i': // Prefix: "images"

				if l := len("images"); len(elem) >= l && elem[0:l] == "images" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						r.name = ImagesPostOperation
						r.summary = "画像アップロード"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/images"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "image_id"
					// Leaf parameter, slashes are prohibited
					idx := strings.IndexByte(elem, '/')
					if idx >= 0 {
						break
					}
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = ImagesImageIDGetOperation
							r.summary = "画像取得"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/images/{image_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

				}

			case 'p': // Prefix: "posts"

				if l := len("posts"); len(elem) >= l && elem[0:l] == "posts" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "GET":
						r.name = PostsGetOperation
						r.summary = "現在のユーザーの投稿一覧取得"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/posts"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = PostsPostOperation
						r.summary = "進捗投稿作成"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/posts"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "post_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = PostsPostIDDeleteOperation
							r.summary = "投稿削除"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/posts/{post_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = PostsPostIDGetOperation
							r.summary = "投稿詳細取得"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/posts/{post_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = PostsPostIDPutOperation
							r.summary = "投稿更新"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/posts/{post_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/reactions"

						if l := len("/reactions"); len(elem) >= l && elem[0:l] == "/reactions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "DELETE":
								r.name = PostsPostIDReactionsDeleteOperation
								r.summary = "投稿からリアクションを削除"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/posts/{post_id}/reactions"
								r.args = args
								r.count = 1
								return r, true
							case "GET":
								r.name = PostsPostIDReactionsGetOperation
								r.summary = "投稿にリアクションしたユーザーの一覧取得"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/posts/{post_id}/reactions"
								r.args = args
								r.count = 1
								return r, true
							case "POST":
								r.name = PostsPostIDReactionsPostOperation
								r.summary = "投稿にリアクション（いいね）を追加"
								r.operationID = ""
								r.operationGroup = ""
								r.pathPattern = "/posts/{post_id}/reactions"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}

					}

				}

			case 't': // Prefix: "timeline"

				if l := len("timeline"); len(elem) >= l && elem[0:l] == "timeline" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = TimelineGetOperation
						r.summary = "タイムライン取得（自分とフレンド）"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/timeline"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'u': // Prefix: "users"

				if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					switch method {
					case "POST":
						r.name = UsersPostOperation
						r.summary = "新規ユーザー登録"
						r.operationID = ""
						r.operationGroup = ""
						r.pathPattern = "/users"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "user_id"
					// Match until "/"
					idx := strings.IndexByte(elem, '/')
					if idx < 0 {
						idx = len(elem)
					}
					args[0] = elem[:idx]
					elem = elem[idx:]

					if len(elem) == 0 {
						switch method {
						case "DELETE":
							r.name = UsersUserIDDeleteOperation
							r.summary = "ユーザーアカウント削除"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/users/{user_id}"
							r.args = args
							r.count = 1
							return r, true
						case "GET":
							r.name = UsersUserIDGetOperation
							r.summary = "ユーザープロフィール取得"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/users/{user_id}"
							r.args = args
							r.count = 1
							return r, true
						case "PUT":
							r.name = UsersUserIDPutOperation
							r.summary = "ユーザープロフィール更新"
							r.operationID = ""
							r.operationGroup = ""
							r.pathPattern = "/users/{user_id}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'f': // Prefix: "friends"

							if l := len("friends"); len(elem) >= l && elem[0:l] == "friends" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = UsersUserIDFriendsGetOperation
									r.summary = "ユーザーのフレンド（フォロー）一覧取得"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/users/{user_id}/friends"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'g': // Prefix: "goals"

							if l := len("goals"); len(elem) >= l && elem[0:l] == "goals" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = UsersUserIDGoalsGetOperation
									r.summary = "指定ユーザーの目標一覧取得"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/users/{user_id}/goals"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'i': // Prefix: "icon"

							if l := len("icon"); len(elem) >= l && elem[0:l] == "icon" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = UsersUserIDIconDeleteOperation
									r.summary = "ユーザーアイコン削除"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/users/{user_id}/icon"
									r.args = args
									r.count = 1
									return r, true
								case "GET":
									r.name = UsersUserIDIconGetOperation
									r.summary = "ユーザーアイコン画像取得"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/users/{user_id}/icon"
									r.args = args
									r.count = 1
									return r, true
								case "POST":
									r.name = UsersUserIDIconPostOperation
									r.summary = "ユーザーアイコンのアップロードまたは置換"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/users/{user_id}/icon"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						case 'p': // Prefix: "posts"

							if l := len("posts"); len(elem) >= l && elem[0:l] == "posts" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = UsersUserIDPostsGetOperation
									r.summary = "指定ユーザーの投稿一覧取得"
									r.operationID = ""
									r.operationGroup = ""
									r.pathPattern = "/users/{user_id}/posts"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			}

		}
	}
	return r, false
}
