// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s FriendsGetOKApplicationJSON) Validate() error {
	alias := ([]uuid.UUID)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s GoalsGetOKApplicationJSON) Validate() error {
	alias := ([]Goal)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s PostsGetOKApplicationJSON) Validate() error {
	alias := ([]Post)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s PostsPostIDReactionsGetOKApplicationJSON) Validate() error {
	alias := ([]Reaction)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s TimelineGetOKApplicationJSON) Validate() error {
	alias := ([]Post)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s UsersUserIDFriendsGetOKApplicationJSON) Validate() error {
	alias := ([]uuid.UUID)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s UsersUserIDGoalsGetOKApplicationJSON) Validate() error {
	alias := ([]Goal)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s UsersUserIDPostsGetOKApplicationJSON) Validate() error {
	alias := ([]Post)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
