// Code generated by ent, DO NOT EDIT.

package image

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldID, id))
}

// ObjectName applies equality check predicate on the "object_name" field. It's identical to ObjectNameEQ.
func ObjectName(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldObjectName, v))
}

// ContentType applies equality check predicate on the "content_type" field. It's identical to ContentTypeEQ.
func ContentType(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldContentType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldCreatedAt, v))
}

// ObjectNameEQ applies the EQ predicate on the "object_name" field.
func ObjectNameEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldObjectName, v))
}

// ObjectNameNEQ applies the NEQ predicate on the "object_name" field.
func ObjectNameNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldObjectName, v))
}

// ObjectNameIn applies the In predicate on the "object_name" field.
func ObjectNameIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldObjectName, vs...))
}

// ObjectNameNotIn applies the NotIn predicate on the "object_name" field.
func ObjectNameNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldObjectName, vs...))
}

// ObjectNameGT applies the GT predicate on the "object_name" field.
func ObjectNameGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldObjectName, v))
}

// ObjectNameGTE applies the GTE predicate on the "object_name" field.
func ObjectNameGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldObjectName, v))
}

// ObjectNameLT applies the LT predicate on the "object_name" field.
func ObjectNameLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldObjectName, v))
}

// ObjectNameLTE applies the LTE predicate on the "object_name" field.
func ObjectNameLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldObjectName, v))
}

// ObjectNameContains applies the Contains predicate on the "object_name" field.
func ObjectNameContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldObjectName, v))
}

// ObjectNameHasPrefix applies the HasPrefix predicate on the "object_name" field.
func ObjectNameHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldObjectName, v))
}

// ObjectNameHasSuffix applies the HasSuffix predicate on the "object_name" field.
func ObjectNameHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldObjectName, v))
}

// ObjectNameEqualFold applies the EqualFold predicate on the "object_name" field.
func ObjectNameEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldObjectName, v))
}

// ObjectNameContainsFold applies the ContainsFold predicate on the "object_name" field.
func ObjectNameContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldObjectName, v))
}

// ContentTypeEQ applies the EQ predicate on the "content_type" field.
func ContentTypeEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldContentType, v))
}

// ContentTypeNEQ applies the NEQ predicate on the "content_type" field.
func ContentTypeNEQ(v string) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldContentType, v))
}

// ContentTypeIn applies the In predicate on the "content_type" field.
func ContentTypeIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldContentType, vs...))
}

// ContentTypeNotIn applies the NotIn predicate on the "content_type" field.
func ContentTypeNotIn(vs ...string) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldContentType, vs...))
}

// ContentTypeGT applies the GT predicate on the "content_type" field.
func ContentTypeGT(v string) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldContentType, v))
}

// ContentTypeGTE applies the GTE predicate on the "content_type" field.
func ContentTypeGTE(v string) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldContentType, v))
}

// ContentTypeLT applies the LT predicate on the "content_type" field.
func ContentTypeLT(v string) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldContentType, v))
}

// ContentTypeLTE applies the LTE predicate on the "content_type" field.
func ContentTypeLTE(v string) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldContentType, v))
}

// ContentTypeContains applies the Contains predicate on the "content_type" field.
func ContentTypeContains(v string) predicate.Image {
	return predicate.Image(sql.FieldContains(FieldContentType, v))
}

// ContentTypeHasPrefix applies the HasPrefix predicate on the "content_type" field.
func ContentTypeHasPrefix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasPrefix(FieldContentType, v))
}

// ContentTypeHasSuffix applies the HasSuffix predicate on the "content_type" field.
func ContentTypeHasSuffix(v string) predicate.Image {
	return predicate.Image(sql.FieldHasSuffix(FieldContentType, v))
}

// ContentTypeEqualFold applies the EqualFold predicate on the "content_type" field.
func ContentTypeEqualFold(v string) predicate.Image {
	return predicate.Image(sql.FieldEqualFold(FieldContentType, v))
}

// ContentTypeContainsFold applies the ContainsFold predicate on the "content_type" field.
func ContentTypeContainsFold(v string) predicate.Image {
	return predicate.Image(sql.FieldContainsFold(FieldContentType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Image {
	return predicate.Image(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Image {
	return predicate.Image(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Image {
	return predicate.Image(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUploadedBy applies the HasEdge predicate on the "uploaded_by" edge.
func HasUploadedBy() predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UploadedByTable, UploadedByColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUploadedByWith applies the HasEdge predicate on the "uploaded_by" edge with a given conditions (other predicates).
func HasUploadedByWith(preds ...predicate.User) predicate.Image {
	return predicate.Image(func(s *sql.Selector) {
		step := newUploadedByStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Image) predicate.Image {
	return predicate.Image(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Image) predicate.Image {
	return predicate.Image(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Image) predicate.Image {
	return predicate.Image(sql.NotPredicates(p))
}
