# 開発環境用 Dockerfile
FROM golang:1.24-alpine AS dev

EXPOSE 8080

WORKDIR /app

# 依存関係の管理用レイヤー（go mod tidyとgo mod download）
COPY go.mod go.sum ./
RUN go mod download && go mod tidy

# ソースコードをコピー
COPY . .

# アプリケーションのビルド用レイヤー
RUN go build -o /main .

# 実行
CMD ["/main"]