// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/goal"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Goal is the model entity for the Goal schema.
type Goal struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Deadline holds the value of the "deadline" field.
	Deadline *time.Time `json:"deadline,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoalQuery when eager-loading is set.
	Edges        GoalEdges `json:"edges"`
	user_goals   *uuid.UUID
	selectValues sql.SelectValues
}

// GoalEdges holds the relations/edges for other nodes in the graph.
type GoalEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Posts holds the value of the posts edge.
	Posts []*Post `json:"posts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoalEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PostsOrErr returns the Posts value or an error if the edge
// was not loaded in eager-loading.
func (e GoalEdges) PostsOrErr() ([]*Post, error) {
	if e.loadedTypes[1] {
		return e.Posts, nil
	}
	return nil, &NotLoadedError{edge: "posts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Goal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goal.FieldTitle:
			values[i] = new(sql.NullString)
		case goal.FieldDeadline, goal.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case goal.FieldID:
			values[i] = new(uuid.UUID)
		case goal.ForeignKeys[0]: // user_goals
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Goal fields.
func (_m *Goal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goal.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case goal.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case goal.FieldDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deadline", values[i])
			} else if value.Valid {
				_m.Deadline = new(time.Time)
				*_m.Deadline = value.Time
			}
		case goal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case goal.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_goals", values[i])
			} else if value.Valid {
				_m.user_goals = new(uuid.UUID)
				*_m.user_goals = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Goal.
// This includes values selected through modifiers, order, etc.
func (_m *Goal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Goal entity.
func (_m *Goal) QueryUser() *UserQuery {
	return NewGoalClient(_m.config).QueryUser(_m)
}

// QueryPosts queries the "posts" edge of the Goal entity.
func (_m *Goal) QueryPosts() *PostQuery {
	return NewGoalClient(_m.config).QueryPosts(_m)
}

// Update returns a builder for updating this Goal.
// Note that you need to call Goal.Unwrap() before calling this method if this Goal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Goal) Update() *GoalUpdateOne {
	return NewGoalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Goal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Goal) Unwrap() *Goal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Goal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Goal) String() string {
	var builder strings.Builder
	builder.WriteString("Goal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Deadline; v != nil {
		builder.WriteString("deadline=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Goals is a parsable slice of Goal.
type Goals []*Goal
